# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ddf6fdb6c6d361779b4da1ee9998dd0c654b06f6427afac26bad2d2780d675cd78217d81c34ccca0c0301ba851315ab17406dfd378d62c9f45f4390b985e68

test:
  secret_key_base: a398df626d1efbb8e00ed6df5c7b8e5d9c718ea2e32e400722ce03b19f41f404cf5b406fee5a4c2500c59c6be33a862345f69fd98c66a6a3afe7d95bbe5c0b26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
